version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: docu-sign-db

    environment:
      POSTGRES_DB: docu_sign
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: docu-sign-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@docusign.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:
  postgres_data: